name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen DB y push a ECR
      run: |
        cd db
        docker build -t tienda-db .
        docker tag tienda-db:latest ${{ secrets.ECR_REPO_URL_DB }}:eks-v1
        docker push ${{ secrets.ECR_REPO_URL_DB }}:eks-v1

    - name: Actualizar configuración de Kubectl con EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Desplegar en Amazon EKS
      run: |
        kubectl apply -f mysql-deployment.yaml -n tienda
        kubectl rollout restart deployment/tienda-db -n tienda